
CREATE OR REPLACE STAGE crime_stage;

USE DATABASE CRIME_DB;
USE SCHEMA ANALYTICS;

COPY INTO STG_LA_CRIME_SILVER
FROM @crime_stage
FILE_FORMAT = (TYPE = PARQUET)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT COUNT(*) FROM STG_LA_CRIME_SILVER;
SELECT * FROM STG_LA_CRIME_SILVER LIMIT 20;

-- First, make sure stage exists
SHOW STAGES IN SCHEMA ANALYTICS;

-- Create stage if needed
CREATE OR REPLACE STAGE CRIME_DB.ANALYTICS.CRIME_STAGE;

